# Generated by Django 4.1 on 2022-12-11 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('harapan_page', '0009_alter_harapandonatur_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harapandonatur',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
